=== issa23i/Lenguaje_de_marcas/U1/U1_T2/liga.dtd
<!ELEMENT liga (partidos+)>
<!ELEMENT partidos (partido+)>
<!ELEMENT partido (equipo+)>
<!ELEMENT equipo (nombre,goles?,tarjetas?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT goles (gol+)>
<!ELEMENT gol EMPTY>
<!ELEMENT tarjetas (tarjeta+)>
<!ELEMENT tarjeta (jugador,color)>
<!ELEMENT jugador (#PCDATA) >
<!ELEMENT color (#PCDATA) >

<!ATTLIST equipo tipo (local|visitante)  #REQUIRED>
<!ATTLIST gol jug CDATA #REQUIRED
          min CDATA #REQUIRED
          pen (si|no) #REQUIRED>

=== issa23i/Lenguaje_de_marcas/U1/U1_T2/liga.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "liga.dtd" >
<liga>
    <partidos>
        <partido>
            <equipo tipo="local">
                <nombre>Zaragoza</nombre>
                <goles>
                    <gol jug="Pepe" min="58" pen="si" />
                    <gol jug="Pepe" min="75" pen="no" />
                </goles>
            </equipo>
            <equipo tipo="visitante">
                <nombre>Numancia</nombre>
                <tarjetas>
                    <tarjeta>
                        <jugador>Manuel</jugador>
                        <color>roja</color>
                    </tarjeta>
                </tarjetas>
            </equipo>
        </partido>
    </partidos>
</liga>
